name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Webhook
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "New `GSX Hub` version is released!"
          description: |
            Version `${{ github.event.release.tag_name }}`
            _ _
            Click [here](${{ github.event.release.html_url }}) to download / see the changelog!
          color: 1b1b1b
          username: GSX Hub
