name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  discordNotification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Webhook (Non-PreRelease)
        uses: sarisia/actions-status-discord@v1.15.1
        if: ${{ github.event.release.prerelease }} == false
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "New `GSX Hub` version is released!"
          description: |
            Version `${{ github.event.release.tag_name }}`
            _ _
            Click [here](${{ github.event.release.html_url }}) to download. Or download automatically via the App!
          color: 1b1b1b
          username: GSX Hub
